### ISSUE TITLE
pom.xml - extra > character

### ISSUE THREAD

**Issue by ghost** [spring-cloud-stream-app-starters/trigger#3]
Line 77 of pom.xml has an extra ">" character causing build problems.

**Comment by sabbyanandan** [comment]
@d-sl: Thanks for reporting it. There's an extra `>` on the 2nd line, and it poorly formatted, too.

```
<pluginRepository>
	<id>spring-releases></id>
	<name>Spring Releases</name>
	<url>http://repo.spring.io/libs-release</url>
</pluginRepository>
```

Surprisingly, our CI plan appears to be green - we will have a look.

**Comment by artembilan** [comment]
I've just pushed some code style refactoring and that's it.
There is indeed no issues in poms on `master`.

And there always has not been: https://github.com/spring-cloud-stream-app-starters/trigger/commit/b1b3d4ead8bebeb279267e7cd47fb4decc7af400#diff-600376dffeb79835ede4a0b285078036

**Comment by ghost** [comment]
I still see the extra character - "<id>spring-releases></id>"  -- am I missing something?

Note that this issue can also be found in other app starter projects.

**Comment by artembilan** [comment]
OK. I see that. It is just an `id` anyway, so doesn't matter what is the text there, since the content has to be just unique withing the current project. Nothing more.
We are fixing this anyway. 

Thank you for the pointer!
